version: '3'

services:

# This config spins up 3 containers: my archlinux mirror, transfer.sh instance and an IRC relay

  mirror:
    build:
      context: .
      dockerfile: Dockerfiles/fancyindex.Dockerfile
    image: alpine-nginx-site-fancyindex:latest
    container_name: archmirror
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      # Rsync crontab syncs the mirror
      - /srv:/srv:ro
      # My TLS certificate from certbot
      - letsencrypt:/etc/letsencrypt:ro
      # Allow to write {access,error}.log
      - /var/log/nginx/mirror.int3nse.com:/var/log/nginx/mirror.int3nse.com
      # Main Nginx config
      - ./sites/mirror/mirror.int3nse.com.conf:/etc/nginx/http.d/mirror.int3nse.com.conf:ro
      # Nginx proxy config for transfer.sh
      - ./sites/transfer/transfer.int3nse.com.conf:/etc/nginx/http.d/transfer.int3nse.com.conf:ro

  transfer:
    image: dutchcoders/transfer.sh:latest
    container_name: transfersh
    command: "--provider local \
      --temp-path /transfer/ \
      --basedir /transfer/ \
      --max-upload-size 3221225 \
      --purge-days 1 \
      --purge-interval 1"
    ports:
      - 8080:8080
    volumes:
      - /transfer:/transfer

  irc-relay:
    build:
      # Pass UID and GID from env to dockerfile to create non-root user in image
      args:
        UID: "${UID}"
        GID: "${GID}"

      context: .
      dockerfile: Dockerfiles/weechat.Dockerfile

    # Name and tag of the image
    image: weechat-relay:latest
    container_name: weechat
    # tty: true
    # Run as the current UID:GID of host executing this
    # user: "${UID}:${GID}"
    secrets:
      - weechat-passphrase
    ports:
      - 9001:9001
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - ./sites/irc-relay:/weechat

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443

    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sites/portainer/:/data


secrets:
   weechat-passphrase:
     file: secrets/weechat-passphrase.txt

volumes:
  letsencrypt:
    driver_opts:
      type: none
      device: /etc/letsencrypt
      o: bind
