version: '3'
name: webservers
services:
# This config spins up 3 containers: my archlinux mirror, transfer.sh instance and an IRC relay
  mirror:
    build:
      context: .
      dockerfile: Dockerfiles/fancyindex.Dockerfile
    image: alpine-nginx-site-fancyindex:latest
    container_name: archmirror
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      # Rsync crontab syncs the mirror
      - /srv:/srv:ro
      # My TLS certificates from certbot
      - letsencrypt:/etc/letsencrypt:ro
      # Certbot renewal challenges
      - acme-challenge:/var/www/.well-known/acme-challenge
      # Allow to write {access,error}.log
      - /var/log/nginx/mirror.int3nse.com:/var/log/nginx/mirror.int3nse.com
      # Main Nginx config
      - ./sites/mirror/mirror.int3nse.com.conf:/etc/nginx/http.d/mirror.int3nse.com.conf:ro
      # the-eye.eu theme
      - ./sites/mirror/indexui:/var/www/indexui:ro
      # Nginx proxy config for transfer.sh
      - ./sites/transfer/transfer.int3nse.com.conf:/etc/nginx/http.d/transfer.int3nse.com.conf
      # Weechat relay blank page for certbot
      - ./sites/irc-relay/irc.int3nse.com.conf:/etc/nginx/http.d/irc.int3nse.com.conf
      # Nginx proxy config for Your Spotify
      - ./sites/your-spotify/yspot.int3nse.com.conf:/etc/nginx/http.d/yspot.int3nse.com.conf
      # Nginx proxy config for Your Spotify server
      - ./sites/your-spotify/yspot-api.int3nse.com.conf:/etc/nginx/http.d/yspot-api.int3nse.com.conf

  transfer:
    image: dutchcoders/transfer.sh:latest
    container_name: transfersh
    command: "--provider local \
      --temp-path /transfer/ \
      --basedir /transfer/ \
      --max-upload-size 3221225 \
      --purge-days 1 \
      --purge-interval 1"
    ports:
      - 8080:8080
    volumes:
      - /transfer:/transfer

########## Your Spotify section start ##########

  ys_server:
    image: yooooomi/your_spotify_server
    container_name: ys_server
    restart: always
    # Can be commented as we are using nginx to connect directly to this container
    # ports:
    #   - "8081:8080"
    links:
      - ys_mongo
    depends_on:
      - ys_mongo
    environment:
      API_ENDPOINT: https://yspot-api.int3nse.com
      # API_ENDPOINT: https://yspot.int3nse.com/api
      CLIENT_ENDPOINT: https://yspot.int3nse.com
      # .env file
      SPOTIFY_PUBLIC: ${SPOTIFY_PUBLIC}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}

  # Your spotify uses an external mongo db
  ys_mongo:
    # Avoid git permission issue
    user: "${UID}:${GID}"
    container_name: mongo
    image: mongo:6
    volumes:
      - ./sites/your-spotify/db:/data/db

  # The actual webpage to connect to
  ys_web:
    image: yooooomi/your_spotify_client
    container_name: ys_web
    restart: always
    # Can be commented as we are using nginx to connect directly to this container
    # ports:
    #   - "8082:3000"
    environment:
      API_ENDPOINT: https://yspot-api.int3nse.com
      # API_ENDPOINT: https://yspot.int3nse.com/api

########## Your Spotify section END ##########

  irc-relay:
    build:
      # Pass UID and GID from env to dockerfile to create non-root user in image
      args:
        UID: "${UID}"
        GID: "${GID}"

      context: .
      dockerfile: Dockerfiles/weechat.Dockerfile

    # Name and tag of the image
    image: weechat-relay:latest
    container_name: weechat
    environment:
      - WEECHAT_HOME=${WEECHAT_HOME}
      - WEECHAT_PASSPHRASE=${WEECHAT_PASSPHRASE}
    # tty: true
    # Run as the current UID:GID of host executing this
    # user: "${UID}:${GID}"
    ports:
      - 9001:9001
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - ./sites/irc-relay:/weechat

volumes:
  letsencrypt:
    driver_opts:
      type: none
      device: /etc/letsencrypt
      o: bind
  acme-challenge:
    driver_opts:
      type: none
      device: /var/www/.well-known/acme-challenge
      o: bind
