version: '3'

services:
  mirror:
    build:
      context: .
      dockerfile: fancyindex.Dockerfile
    container_name: archmirror
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv:/srv:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx/mirror.int3nse.com:/var/log/nginx/mirror.int3nse.com
      - ./sites/mirror.int3nse.com.conf:/etc/nginx/http.d/mirror.int3nse.com.conf:ro
      - ./sites/transfer.int3nse.com.conf:/etc/nginx/http.d/transfer.int3nse.com.conf:ro

  transfer:
    image: dutchcoders/transfer.sh:latest
    container_name: transfersh
    command: "--provider local \
      --temp-path /transfer/ \
      --basedir /transfer/ \
      --max-upload-size 3221225 \
      --purge-days 1 \
      --purge-interval 1"
    ports:
      - 8080:8080
    volumes:
      - /transfer:/transfer




# sudo docker run -p 8080:8080 -v /transfer:/transfer --rm --name transfersh dutchcoders/transfer.sh:latest --provider local --temp-path /transfer/ --basedir /transfer/ --max-upload-size 3221225 --purge-days 1 --purge-interval 1