version: "3"

services:
  myalpine:
    image: alpine
    build:
      args:
          UID: "${UID}"
          GID: "${GID}"
      context: .
    cap_add:
      - ALL
    container_name: playground
    tty: true
    environment:
      - PASS="${MYPASS}"
    volumes:
      - secrets:/run/secrets:ro
      - letsencrypt:/etc/letsencrypt:ro

  secrets:
    image: vault
    container_name: vault
    cap_add:
      - ALL
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    volumes:
      - secrets:/secrets:rw
      - ./config.hcl:/config.hcl
    command: ["vault", "server" ,"-dev", "-dev-root-token-id=myroot"]
    # command: ["vault", "server", "-config=/config.hcl" ,"-dev", "-dev-root-token-id=myroot"]
    ports:
      - "8200:8200"

volumes:
  secrets:

  letsencrypt:
    driver_opts:
      type: none
      device: /etc/letsencrypt
      o: bind
